[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'forge-cache'
fs_permissions = [{ access = "read-write", path = "./"},{ access = "write", path = "./svgs"}]

solc_version = '0.8.21'
evm_version = 'paris'
optimizer = true
optimizer_runs = 10
ignored_error_codes = []
no_match_path = "script/svg/*"

via_ir = true

# Mainnet libraries:
# libraries = [
#   'contracts/libraries/ActionLib.sol:ActionLib:0x7990dac84e3241fe314b980bba1466ac08715c4f',
#   'contracts/libraries/FollowLib.sol:FollowLib:0xe280cb21fb36b6b2d584428b809a6b822a5c2260',
#   'contracts/libraries/GovernanceLib.sol:GovernanceLib:0x8a83227dbf5c80b1f693de63babe168c59fefd6b',
#   'contracts/libraries/LegacyCollectLib.sol:LegacyCollectLib:0x189f3fecc93d4b563d4061a3ffa5fffd0d0f53a0',
#   'contracts/libraries/MetaTxLib.sol:MetaTxLib:0xf191c489e4ba0f448ea08a5fd27e9c928643f5c7',
#   'contracts/libraries/MigrationLib.sol:MigrationLib:0x0deced9ac3833b687d69d4eac6655f0f1279acee',
#   'contracts/libraries/ProfileLib.sol:ProfileLib:0x3fce2475a92c185f9634f5638f6b33306d77bb10',
#   'contracts/libraries/PublicationLib.sol:PublicationLib:0x90654f24a2c164a4da8f763ac8bc032d3d083a1b',
#   'contracts/libraries/ValidationLib.sol:ValidationLib:0x9cafd24d2851d9eb56e5a8fd394ab2ac0ef99849',
# ]

# Testnet libraries:
# libraries = [
# 	"contracts/libraries/ActionLib.sol:ActionLib:0x6099032c8d4b93d25A50a8F0A6E2cc66259103bc",
# 	"contracts/libraries/FollowLib.sol:FollowLib:0x7289854FF2e55c43AFCB895EC8cAE798811fcc2D",
# 	"contracts/libraries/GovernanceLib.sol:GovernanceLib:0xf32f16af9e44cB92311DE854D138547BC1F91DC7",
# 	"contracts/libraries/LegacyCollectLib.sol:LegacyCollectLib:0xCCF77B802160326282F260bb6e275333fEA9E76C",
# 	"contracts/libraries/MetaTxLib.sol:MetaTxLib:0x7Afc131Fc22A703e39694c11003E55b9301BaBd7",
# 	"contracts/libraries/MigrationLib.sol:MigrationLib:0xA4ad0E98a19581C8aB0426478d3aBcE83476554d",
# 	"contracts/libraries/ProfileLib.sol:ProfileLib:0x653FB436CE5523d9607339C90d2D361396d699DA",
# 	"contracts/libraries/PublicationLib.sol:PublicationLib:0x37CBD2C689A8eb10459D974A824ADEF74124DC7e",
# 	"contracts/libraries/ValidationLib.sol:ValidationLib:0x1a4D3f97770925A14997B351C5cC3Cd47192a5B8",
# ]

[rpc_endpoints]
polygon = "${POLYGON_RPC_URL}"
mumbai = "${MUMBAI_RPC_URL}"
amoy = "${AMOY_RPC_URL}"
local = "${LOCAL_RPC_URL}"

[fuzz]
runs = 50
max_test_rejects = 200000

[profile.cibuild]
via_ir = true
libraries = []

[profile.citest]
via_ir = false
ignored_error_codes = ["license", "code-size"]
libraries = []

[profile.citest.fuzz]
runs = 100
