[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'forge-cache'
fs_permissions = [{ access = "read-write", path = "./"},{ access = "write", path = "./svgs"}]

solc_version = '0.8.21'
evm_version = 'paris'
optimizer = true
optimizer_runs = 10
ignored_error_codes = []
# via_ir = true

# libraries = [
#   'contracts/libraries/ActionLib.sol:ActionLib:0x7990dac84e3241fe314b980bba1466ac08715c4f',
#   'contracts/libraries/FollowLib.sol:FollowLib:0xe280cb21fb36b6b2d584428b809a6b822a5c2260',
#   'contracts/libraries/GovernanceLib.sol:GovernanceLib:0x5268512d20bf7653cf6d54b7c485ae3fbc658451',
#   'contracts/libraries/LegacyCollectLib.sol:LegacyCollectLib:0x5f0f24377c00f1517b4de496cf49eec8beb4ecb4',
#   'contracts/libraries/MetaTxLib.sol:MetaTxLib:0xf191c489e4ba0f448ea08a5fd27e9c928643f5c7',
#   'contracts/libraries/MigrationLib.sol:MigrationLib:0x0deced9ac3833b687d69d4eac6655f0f1279acee',
#   'contracts/libraries/ProfileLib.sol:ProfileLib:0x3fce2475a92c185f9634f5638f6b33306d77bb10',
#   'contracts/libraries/PublicationLib.sol:PublicationLib:0x90654f24a2c164a4da8f763ac8bc032d3d083a1b',
#   'contracts/libraries/ValidationLib.sol:ValidationLib:0x9cafd24d2851d9eb56e5a8fd394ab2ac0ef99849',
#   'contracts/libraries/token-uris/FollowTokenURILib.sol:FollowTokenURILib:0xc58f0e2a361e35c08619ef5f6122dc15180d783e',
#   'contracts/libraries/token-uris/HandleTokenURILib.sol:HandleTokenURILib:0x0e20f112689c7894ab8142108574e45d2650f529',
#   'contracts/libraries/token-uris/ProfileTokenURILib.sol:ProfileTokenURILib:0xf167835e74eecfe4bc571701d34fd38f4b61a830'
# ]

[rpc_endpoints]
polygon = "${POLYGON_RPC_URL}"
mumbai = "${MUMBAI_RPC_URL}"

[fuzz]
runs = 50
max_test_rejects = 200000

[profile.cibuild]
via_ir = true
libraries = []

[profile.citest]
via_ir = false
ignored_error_codes = ["license", "code-size"]
libraries = []

[profile.citest.fuzz]
runs = 100
